In [2]:
import os

# Check files inside the directory
file_path = "../data/raw/bbmp/"
print("Files in bbmp directory:")
print(os.listdir(file_path))

Files in bbmp directory:
['citizen-grievances.csv']

In [3]:
import os

path = "../data/raw/bbmp/citizen-grievances.csv"

print("Is it a folder?", os.path.isdir(path))
print("Is it a file?", os.path.isfile(path))

Is it a folder? True
Is it a file? False

In [4]:
import pandas as pd

# Target the actual CSV file inside the unzipped folder
df = pd.read_csv("../data/raw/bbmp/citizen-grievances.csv/citizen-grievances.csv")

print("=== SHAPE ===")
print(df.shape)

print("\n=== DATA INFO ===")
df.info()

print("\n=== FIRST 3 ROWS ===")
df.head(3)

=== SHAPE ===
(1230890, 12)

=== DATA INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 1230890 entries, 0 to 1230889
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Complaint ID       1230890 non-null  int64
 1   Category           1230890 non-null  str
 2   Sub Category       1230890 non-null  str
 3   Grievance Date     1230890 non-null  str
 4   Zone Name          1230303 non-null  str
 5   Ward Name          1230890 non-null  str
 6   Grievance Mode     1230303 non-null  str
 7   Grievance Status   1230833 non-null  str
 8   Staff Remarks      1207854 non-null  str
 9   Staff Name         1230833 non-null  str
 10  Staff Designation  1230303 non-null  str
 11  Rating             40100 non-null    float64
dtypes: float64(1), int64(1), str(10)
memory usage: 112.7 MB

=== FIRST 3 ROWS ===

,Complaint ID,Category,Sub Category,Grievance Date,Zone Name,Ward Name,Grievance Mode,Grievance Status,Staff Remarks,Staff Name,Staff Designation,Rating
0,21236361,Electrical,Street Light Not Working,2026-08-21 10:32:00,RRNagar,Jnanabharathi Ward,Nammabengaluru App,Registered,1st Assignment Based on Ward Mapping,Sangamesh/JE,Sangamesh/JE,NaN
1,21236360,Electrical,Street Light Not Working,2026-08-21 10:25:00,South,J.P.Nagar,Nammabengaluru App,Registered,1st Assignment Based on Ward Mapping,Shreyas V/AE,Shreyas V/AE,NaN
2,21236359,Road Maintenance(Engg),footpath encroachment,2026-08-21 10:25:00,West,K.R.Market,Nammabengaluru App,Registered,1st Assignment Based on Ward Mapping,Arun Kumar M/AE,Arun Kumar M/AE,NaN

In [5]:
# 1. Standardize column names to lowercase with underscores
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# 2. Convert Grievance Date to proper datetime
df['grievance_date'] = pd.to_datetime(df['grievance_date'])

# 3. Convert repeated text fields to categorical dtypes to save memory
cat_cols = ['category', 'sub_category', 'zone_name', 'grievance_mode', 'grievance_status']
for col in cat_cols:
    df[col] = df[col].astype('category')

# Print clean summary
print("=== UPDATED DATA TYPES & MEMORY ===")
df.info()

=== UPDATED DATA TYPES & MEMORY ===
<class 'pandas.DataFrame'>
RangeIndex: 1230890 entries, 0 to 1230889
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   complaint_id       1230890 non-null  int64
 1   category           1230890 non-null  category
 2   sub_category       1230890 non-null  category
 3   grievance_date     1230890 non-null  datetime64[us]
 4   zone_name          1230303 non-null  category
 5   ward_name          1230890 non-null  str
 6   grievance_mode     1230303 non-null  category
 7   grievance_status   1230833 non-null  category
 8   staff_remarks      1207854 non-null  str
 9   staff_name         1230833 non-null  str
 10  staff_designation  1230303 non-null  str
 11  rating             40100 non-null    float64
dtypes: category(5), datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 72.8 MB

In [6]:
## easier version of above code
# Step 1: Easy column names
df.columns = [
    'complaint_id', 'category', 'sub_category', 'grievance_date',
    'zone_name', 'ward_name', 'grievance_mode', 'grievance_status',
    'staff_remarks', 'staff_name', 'staff_designation', 'rating'
]

# Step 2: Make dates real calendar dates
df['grievance_date'] = pd.to_datetime(df['grievance_date'])

# Step 3: Show missing values
print("=== MISSING VALUES PER COLUMN ===")
print(df.isnull().sum())

=== MISSING VALUES PER COLUMN ===
complaint_id               0
category                   0
sub_category               0
grievance_date             0
zone_name                587
ward_name                  0
grievance_mode           587
grievance_status          57
staff_remarks          23036
staff_name                57
staff_designation        587
rating               1190790
dtype: int64

In [7]:
df['rating']=df['rating'].fillna(0)

In [8]:
df['rating'].isnull().sum()

np.int64(0)

In [9]:
# 1. List of text columns that have missing values
text_columns = ['zone_name', 'grievance_mode', 'grievance_status', 'staff_remarks', 'staff_name', 'staff_designation']

# 2. Convert them to string and fill missing values in one line
for col in text_columns:
    df[col] = df[col].astype(str).fillna('Unspecified')

In [10]:
df.isnull().sum()

complaint_id         0
category             0
sub_category         0
grievance_date       0
zone_name            0
ward_name            0
grievance_mode       0
grievance_status     0
staff_remarks        0
staff_name           0
staff_designation    0
rating               0
dtype: int64

In [11]:
df['rating_given'] = (df['rating'] > 0).astype(int)

In [12]:
# Fill missing values in the original 'rating' column with 0 (or a neutral score like 0.0)
df['rating'] = df['rating'].fillna(0)

# Verify that there are no remaining missing values in 'rating'
print("Missing values in 'rating':", df['rating'].isnull().sum())
df[['rating', 'rating_given']].head()

Missing values in 'rating': 0

   rating  rating_given
0     0.0             0
1     0.0             0
2     0.0             0
3     0.0             0
4     0.0             0

In [13]:
# Identify all text (object) columns
text_columns = df.select_dtypes(include=['object']).columns

# Strip extra spaces and convert to lowercase
for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.lower()

# Verify text columns
df[text_columns].head()

C:\Users\PRAPTHI SALIAN\AppData\Local\Temp\ipykernel_8440\3758093570.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

,zone_name,ward_name,grievance_mode,grievance_status,staff_remarks,staff_name,staff_designation
0,rrnagar,jnanabharathi ward,nammabengaluru app,registered,1st assignment based on ward mapping,sangamesh/je,sangamesh/je
1,south,j.p.nagar,nammabengaluru app,registered,1st assignment based on ward mapping,shreyas v/ae,shreyas v/ae
2,west,k.r.market,nammabengaluru app,registered,1st assignment based on ward mapping,arun kumar m/ae,arun kumar m/ae
3,c.v. raman nagar,indiranagar,-select-,registered,1st assignment based on ward mapping,nayana s/je,nayana s/je
4,jayanagar,beguru,bswml control room,registered,1st assignment based on ward mapping,marshal ward no 192/marshal,marshal ward no 192/marshal

In [15]:
import numpy as np

# Replace dummy placeholder strings with actual missing values (NaN)
df['grievance_mode'] = df['grievance_mode'].replace('-select-', np.nan)

# Check missing value count in grievance_mode
print("Missing values in 'grievance_mode':", df['grievance_mode'].isnull().sum())
df[['grievance_mode', 'grievance_status']].head()

Missing values in 'grievance_mode': 224

       grievance_mode grievance_status
0  nammabengaluru app       registered
1  nammabengaluru app       registered
2  nammabengaluru app       registered
3                 NaN       registered
4  bswml control room       registered

In [16]:
# Fill missing values in 'grievance_mode' with 'unknown'
df['grievance_mode'] = df['grievance_mode'].fillna('unknown')

# Verify no missing values remain in 'grievance_mode'
print("Missing values in 'grievance_mode':", df['grievance_mode'].isnull().sum())
df[['grievance_mode', 'grievance_status']].head()

Missing values in 'grievance_mode': 0

       grievance_mode grievance_status
0  nammabengaluru app       registered
1  nammabengaluru app       registered
2  nammabengaluru app       registered
3             unknown       registered
4  bswml control room       registered

In [17]:
# List staff-related columns
staff_cols = ['staff_remarks', 'staff_name', 'staff_designation']

# Fill missing values in staff columns with 'not assigned'
df[staff_cols] = df[staff_cols].fillna('not assigned')

# Verify no missing values remain in these columns
print("Remaining missing values in staff columns:")
print(df[staff_cols].isnull().sum())
df[staff_cols].head()

Remaining missing values in staff columns:
staff_remarks        0
staff_name           0
staff_designation    0
dtype: int64

,staff_remarks,staff_name,staff_designation
0,1st assignment based on ward mapping,sangamesh/je,sangamesh/je
1,1st assignment based on ward mapping,shreyas v/ae,shreyas v/ae
2,1st assignment based on ward mapping,arun kumar m/ae,arun kumar m/ae
3,1st assignment based on ward mapping,nayana s/je,nayana s/je
4,1st assignment based on ward mapping,marshal ward no 192/marshal,marshal ward no 192/marshal

In [18]:
# Check total duplicate rows before dropping
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows found: {duplicate_count}")

# Drop exact duplicate rows
df = df.drop_duplicates()

# Confirm shape after dropping duplicates
print(f"Dataset shape after deduplication: {df.shape}")

Total duplicate rows found: 0
Dataset shape after deduplication: (1230890, 13)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1230890 entries, 0 to 1230889
Data columns (total 13 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   complaint_id       1230890 non-null  int64
 1   category           1230890 non-null  category
 2   sub_category       1230890 non-null  category
 3   grievance_date     1230890 non-null  datetime64[us]
 4   zone_name          1230890 non-null  str
 5   ward_name          1230890 non-null  str
 6   grievance_mode     1230890 non-null  str
 7   grievance_status   1230890 non-null  str
 8   staff_remarks      1230890 non-null  str
 9   staff_name         1230890 non-null  str
 10  staff_designation  1230890 non-null  str
 11  rating             1230890 non-null  float64
 12  rating_given       1230890 non-null  int64
dtypes: category(2), datetime64[us](1), float64(1), int64(2), str(7)
memory usage: 106.8 MB

In [21]:
# Convert text columns to category dtype to optimize memory usage
str_cols = ['zone_name', 'ward_name', 'grievance_mode', 'grievance_status', 'staff_designation']

for col in str_cols:
    df[col] = df[col].astype('category')

# Check updated memory usage
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1230890 entries, 0 to 1230889
Data columns (total 13 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   complaint_id       1230890 non-null  int64
 1   category           1230890 non-null  category
 2   sub_category       1230890 non-null  category
 3   grievance_date     1230890 non-null  datetime64[us]
 4   zone_name          1230890 non-null  category
 5   ward_name          1230890 non-null  category
 6   grievance_mode     1230890 non-null  category
 7   grievance_status   1230890 non-null  category
 8   staff_remarks      1230890 non-null  str
 9   staff_name         1230890 non-null  str
 10  staff_designation  1230890 non-null  category
 11  rating             1230890 non-null  float64
 12  rating_given       1230890 non-null  int64
dtypes: category(7), datetime64[us](1), float64(1), int64(2), str(2)
memory usage: 68.1 MB

In [23]:
# Save clean dataset to your data folder
df.to_csv('../data/civicsense_cleaned.csv', index=False)
print("Cleaned dataset successfully saved to '../data/civicsense_cleaned.csv'!")

Cleaned dataset successfully saved to '../data/civicsense_cleaned.csv'!

In [24]:
import os

# Get the absolute full path of your cleaned CSV file
file_path = os.path.abspath('../data/civicsense_cleaned.csv')

print("Your file is saved here:")
print(file_path)

Your file is saved here:
C:\Users\PRAPTHI SALIAN\Documents\important placement\civicsense\data\civicsense_cleaned.csv